  
@baseUrl=https://extractionxxpsq.azurewebsites.net
@apiKey=YourSecretKeyCanBeAnything

GET {{baseUrl}}
###

POST {{baseUrl}}/api/extraction
Ocp-Apim-Subscription-Key: {{apiKey}}
Content-Type: application/json

< ../postman_request.json